name: CI/CD security

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  security-scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
      packages: read

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Build e testes (JUnit)
        run: mvn clean test

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: java

      - name: Build for CodeQL Analysis
        run: mvn clean compile

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v4

      - name: Complete scan with Trivy
        uses: aquasecurity/trivy-action@0.35.0
        with:
          scan-type: "fs"
          scanners: "vuln,secret,config"
          severity: "CRITICAL,HIGH"
          format: "sarif"
          output: "trivy-results.sarif"
          cache: "true"

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: trivy-results.sarif

      - name: Upload artifact to pipeline metadata
        uses: actions/upload-artifact@v4
        with:
          name: Generate artifact with Trivy result
          path: trivy-results.sarif

  build-and-push:
    runs-on: ubuntu-latest
    needs: security-scan
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Build for AMD64 (to scan the image)
      - name: Build Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          #tags: ${{ steps.meta.outputs.tags }}
          tags: local/tasklist-phase1:scan
          #labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          push: false
          load: true

      # Scan with Trivy
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.35.0
        with:
          scan-type: image
          #image-ref: ${{ steps.meta.outputs.tags }}
          image-ref: local/tasklist-phase1:scan
          scanners: vuln
          format: sarif
          output: trivy-image-results.sarif
          exit-code: '0'

      - name: Upload artifact to pipeline metadata
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Generate artifact with Trivy image result
          path: trivy-image-results.sarif
          if-no-files-found: warn

      - name: Push Docker image (multi-arch)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          push: true